apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ms-catalog
  namespace: my-project
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: ms-catalog.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ms-catalog
                port:
                  number: 8083
