name: CI - Build & Test ms-cart

on:
  push:
    branches:
      - future
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # 3. Make Gradle executable
      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      # 4. Build with Gradle (skip tests for faster build)
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # 5. Run tests
      - name: Run tests
        run: ./gradlew test

      # 6. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 7. Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 8. Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ms-cart:dev

      # 9. Verify image pushed
      - name: Verify image pushed
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/ms-cart:dev
